repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
      exclude: ^(cluster/|apps/k8s/manifests/)
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.78.0
  hooks:
    - id: terraform_fmt
