name: auto-release

on:
  push:
    branches: [main]

jobs:
  semver:
    runs-on: terraform-runner
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
          prerelease: false
          config-name: auto-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
