name: tfsec
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tfsec:
    name: tfsec
    runs-on: {{ cookiecutter.github_runner }}
    strategy:
      matrix:
        app:
          - environments/dev
          - environments/qa
          - environments/stage
          - environments/prod
          - init


    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true
          working_directory: .devops/apps/{{ matrix.app }}
