version: 0.1

projects:
  - path: .devops/apps/init
  - path: .devops/apps/environments/dev
  - path: .devops/apps/environments/qa
  - path: .devops/apps/environments/stage
  - path: .devops/apps/environments/prod
