apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-apps
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: cluster/base
    repoURL: {{ cookiecutter.github_foundation_repo }}
    targetRevision: local
    helm:
      valueFiles:
        - local-values.yaml
