envName: local

default:
  app:
    destination:
      namespace: local
      server: https://kubernetes.default.svc
    project: default
    source:
      targetRevision: local

applications:
  helm-guestbook:
    enabled: true
    enableAutoSync: true

  sealed-secrets:
    enabled: true
    enableAutoSync: true

  prometheus:
    enabled: true
    enableAutoSync: true

  dashboard:
    enabled: true
    enableAutoSync: true
