apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ cookiecutter.project_slug }}-certificate
  namespace: default
spec:
  secretName: {{ cookiecutter.project_slug }}-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  # TODO: define domain correctly
  - example.com
  - '*.example.com'
