apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-test
  namespace: cert-manager
spec:
  acme:
    email: {{ cookiecutter.devops_email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-test-account-key
    solvers:
    - selector: {}
      dns01:
        # TODO: add dns config

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: {{ cookiecutter.devops_email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - selector: {}
      dns01:
        # TODO: add dns config
