name: auto-release

on:
  push:
    branches: [main]

jobs:
  semver:
    runs-on: {{ cookiecutter.github_runner }}
    if: ${{ false }}  # disable for now
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
          prerelease: false
          config-name: auto-release.yml
        env:
          GITHUB_TOKEN: ${% raw %}{{ secrets.GITHUB_TOKEN }}{% endraw %}
