name: 'execute-tf-init'
on:
  pull_request:
      paths:
      - 'apps/init/**'
      - '.github/workflows/execute-tf-init.yaml'
  push:
      paths:
      - 'apps/init/**'
      - '.github/workflows/execute-tf-init.yaml'
      branches:
      - main

jobs:
  terraform:
    name: 'Terraform CI'
    runs-on: {{ cookiecutter.github_runner }}
    defaults:
      run:
        working-directory: ${% raw %}{{ env.working-directory }}{% endraw %}
    env:
      working-directory: ./apps/init

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    # - name: Invalidate lock
    #   id: invalidate-lock
    #   run: terraform force-unlock -force XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Reformat Plan
      id: colored-plan
      run: |
        echo '${% raw %}{{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}{% endraw %}'' \
        | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > plan.txt

    - name: Put Plan in Env Var
      run: |
        PLAN=$(cat plan.txt)
        echo "PLAN<<EOF" >> $GITHUB_ENV
        echo "$PLAN" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Post Plan and Apply to GitHub PR
      uses: mshick/add-pr-comment@v1
      with:
        repo-token: ${% raw %}{{ secrets.GITHUB_TOKEN }}{% endraw %}
        repo-token-user-login: 'github-actions[bot]'
        message: |
          Plan for **apps/init**:

          ```diff
          ${% raw %}{{ env.PLAN }}{% endraw %}
          ```

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
