---
- name: Create cluster on kind
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Check if {{ cookiecutter.kind_cluster_name }} cluster is created on kind
      command: kind get clusters
      register: cluster_check
    - name: Create cluster on kind named {{ cookiecutter.kind_cluster_name }}
      command: kind create cluster --name {{ cookiecutter.kind_cluster_name }}
      when: not '{{ cookiecutter.kind_cluster_name }}' in cluster_check.stdout_lines
