---
- name: Install ArgoCD
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create argocd namespace
      kubernetes.core.k8s:
        name: argocd
        api_version: v1
        kind: Namespace
        state: present
    - name: Download argocd manifest to the cluster.
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
        dest: ./manifests/argocd/install.yaml
        mode: "0664"
    - name: Apply argocd manifest to the cluster.
      kubernetes.core.k8s:
        src: ./manifests/argocd/install.yaml
        state: present
        namespace: argocd
