repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
      files: \.devops/.*\.yml
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.78.0
  hooks:
    - id: terraform_fmt
      files: \.devops/.*\.tf
